# General Config #
title: Ops Blog
email: dennis@bigpanda.io
description: >- # this means to ignore newlines until "baseurl:"
  Dennis Zheleznyak @denzhel writings on ops, development and more.
url: "http://denzhel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  denzhel

# Theme Configurations #
theme: plainwhite
plainwhite:
  name: Dennis Zheleznyak
  tagline: | 
    DevOps Engineer
          bigpanda
  date_format: "%b %-d, %Y"
  social_links:
    github:  denzhel
  show_excerpts: true

# Plugins #
plugins:
  - jekyll-feed

